### ISSUE TITLE
Error in format of CPL file

### ISSUE THREAD

**Issue by RDDyer** [Neumi/tmc2209_devboard#4]
The csv file that JLCPCB uses for the Assembly process appears to have an error in it. When I submitted the Production ZIP file I got an error because they want the last two columns of the file to be Layer and then Rotation. The existing file has them switched. It was an easy edit, but since this was my first time ordering an Assembly, it confused me for a little while. 

Also huge thanks to you for creating this project. As you said the price for 5 assembled boards is just over $50 with 1/3 of that being shipping. The other problem was that they were out of the current sense resistors, so I'll order them from DigiKey and solder them by hand. 

Really excited to try them out.

**Comment by Neumi** [comment]
Thanks!
I tried to reproduce the error. The files seem right to me. I used version 103 with these files: 
Gerber:
https://github.com/Neumi/tmc2209_devboard/blob/master/hardware/version103/production.zip
BOM:
https://github.com/Neumi/tmc2209_devboard/blob/master/hardware/version103/production/tmc2209_devboard.csv
Position:
https://github.com/Neumi/tmc2209_devboard/blob/master/hardware/version103/production/tmc2209_devboard-top-pos.csv

<img width="1440" alt="Screenshot 2023-05-23 at 10 38 39" src="https://github.com/Neumi/tmc2209_devboard/assets/9141110/0a899faf-6018-46b5-8d91-3fb1ac914c49">

Let me know if you need any help. If the boards arrive, I would love to see a picture of them in action!

**Comment by RDDyer** [comment]
Thank you for checking. As this was my first attempt at using JLCPCB I wasn't confident of my process. Now I'm not sure which file I was using. I did check the file myself, and the columns were reversed in the file, just as the error said. I hope I didn't use the wrong version. I'm pretty sure I was using v103. I hope I didn't screw up my order. Yikes!!
  
 The PCBs are 29% finished at this time. I ordered black solder mask with white silkscreen. I'll send you a pic when they arrive, but I'm not sure how soon I'll have them actually running. I'm headed out of the country for almost all of June, just shortly after the boards arrive. If I don't have any trouble using the sample code, they'll probably come right up.
  
 Thanks again for providing this board to the community. I haven't seen many 2209 boards out there, especially with an UNO shield form factor.
  
  
  

----------------------------------------

**Comment by RDDyer** [comment]
Hello,
  
 I thought I'd let you know that my (5) assembled boards arrived from JLCPCB. I don't know if anyone has done a white on black board before, so here's an example. The component layout looks right, and the silkscreen says v1.3, so hopefully I gave them all the correct files in spite of my confusion.
  
 I won't have the chance to try one until next week because JLCPCB did not have the current sense resistors in stock, so I'm awaiting my DigiKey order. I ordered some resistors (and the XT-30 connectors) from a distributor in Poland, but they only had the correct resistor values in a 2512 package. I tried soldering them, but I don't like how they look, and I can't see under them to know if all is well. I don't want to blow a chip due to poor soldering.
  
 Anyway, thanks again for making all your talent and hard work available to the community.
  
  
  

----------------------------------------

**Comment by Neumi** [comment]
This should not be such a big problem. The parts I changed were the capacitor and resistor for the reset button and the one part number of the Vsens resistor (was 10 ohm accidentally changed to 10k). Therefore JLC would have complained that they cant place the parts I guess :D Let me know if you made progress! :) 

Oh and if you're from Poland... there is an ebay seller selling the exact 10mOhm 2012 shunt resistors for an ok price. I needed them too for Ethersweep.

**Comment by RDDyer** [comment]
I have one board completed, and I plugged it into an UNO. I compiled and uploaded your sample program without error (after I downloaded the TMCStepper library).
  
 Unfortunately (kinda) I leave for my annual vacation in the US tomorrow, so progress is halted for a while. I'll get back to you in July after I have my first motor turning. I'm getting excited!! :))
  
 PS: Do you have any idea how many people have fabricated and are using your board?
  

----------------------------------------

**Comment by Neumi** [comment]
That's great news! Have fun!
Remember to use the right location for the motor connector. For standard pin setting, the outermost one is the one that works. But to be checked for each motor/cable combination. But it won't catch on fire if done wrong (better start with lower motor voltage though). Just to keep this in mind when the motor behaves strangely (jitters or vibrates but not turns).

I have no clue actually. I can only see a handful of people cloned the repo and the traffic on the page. But not how many downloaded or actually built the board. It would be great to have some tracking about built boards. Maybe I find a manufacturer, that builds and distributes them for me. I was in contact with a few companies for other projects. Maybe it's worth a try.
